spring:
  rabbitmq:
    host: localhost
  cloud:
    config:
      server:
        git:
          searchPaths: '{application},{application}/{profile}'
          cloneOnStart: true
          force-pull: true
          repos:
            lourdes-config-repo:
              pattern: lourdes*
              uri: http://10.49.160.52:8080/r/svn-arch/template-spring-boot-config.git
              searchPaths: '{application},{application}/{profile}'
              cloneOnStart: false
              force-pull: true
